request-yo-racks/api

- .coafile
- .gitignore
- Makefile
- api/apps/api/collectors/collector.py
- api/apps/api/tests/test_collectors.py
- api/apps/api/tests/test_integration_collectors.py
- api/celery/tasks.py
- docs/source/collectors/collectors.rst
- docs/source/collectors/modules.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/usage.rst
- requirements/_base.txt
- requirements/_docs.txt
- requirements/_tests.txt
- tox.ini
A collector is an object having the ability to collect information from
a specific provider (i.e. 'yelp' or 'google').
Miscellaneous items:
* Update `.gitignore` file
* Update Makefile
* Update test dependencies:
* Add `Faker`
* Add `pytest-mock`
* Update Sphinx documentation structure
* Update the documentation
* Use the basicstrap sphinx theme for the documentation
* Add unit tests
* Fix tox.ini
* Fix coala
* The output is broken in the `pre` version
(see https://github.com/coala/coala/pull/4420 for more details)
* Ensure the `ci-*` targets are passing
This patch implements a Google and a Yelp collector as well as a generic
client collector which abstracts all the mechanisms to authenticate and
retrieve the exact information we want.
Mostly by hand, but implements a few basic unit tests …
> Implement collectors

- .coveragerc
- Makefile
- api/apps/api/collectors/collector.py
- api/apps/api/tests/google_collector_details_epoch_coffee.json
- api/apps/api/tests/google_collector_search_epoch_coffee.json
- api/apps/api/tests/test_collectors.py
- api/apps/api/tests/test_integration_collectors.py
- api/apps/api/tests/test_test.py
* Add YelpCollector tests
* Add GoogleCollector tests
* Clean up
More testing is always good.
`make ci-coala && make ci-docs && make ci-tests`
> Improve unit tests

- .github/PULL_REQUEST_TEMPLATE.md
Description
-----------
The Github PR template was not rendering correctly when used with hub
command line tool.
Not having to re-format the PR manually.
> Fix the Github PR template

- .circleci/config.yml
- .gitignore
- Dockerfile.dev
- Makefile
- api/settings/base.py
- setup.cfg
- setup.py
- tox.ini
Description
-----------
* Polish the `Dockerfile.dev` image
* Update the Makefile to add:
* The ability to use a `dev` Dockerfile
* Run the administrative tasks locally or inside a container
* Update CircleCI configuration
* Leverage tox to perform all python related operations
Make the setup simpler and offer the ability to run the administrative
tasks locally or inside a container.
Manually.
- Breaking change (fix or feature that would cause existing functionality to change)
Checklist
---------
> Refactor the setup

- .circleci/config.yml
- Makefile
- setup.cfg
Description
-----------
* Update the dependencies.
* Reorganize the targets with more sensible names and fixes the `django-*`
rules.
Trying to make this project super esy to use.
Manually.
Checklist
---------
> Update Makefile and dependencies

- Dockerfile.dev
- Makefile
- api/settings/base.py
- tools/kubernetes-django-manage.sh
Description
-----------
* Implement unimplemented Makefiel targets
* Create script to run the `manage.py` django commandis directly on a
kubernetes pod
* Remove SQLlite as the default database
* Update Makefile
Still running the quest of making this project super easily usable.
Manually.
Checklist
---------
> Make general improvements

- Dockerfile
- Makefile
- docker/api/django-entrypoint.sh
Description
-----------
Creates a Dockerfile that will be used for releases. This image uses the
multistage build feature to considerably reduce the size of the final
artifact.
Drive-by:
* Adjust the `django-entrypoint.sh` script
* Use the release `Dockerfile` by default in the `Makefile`
Creating an image that could be promoted from dev to staging, to production.
Manually.
Screenshots (if appropriate)
----------------------------
- New feature (non-breaking change which adds functionality)
Checklist
---------
> Create a Dockerfile

- Makefile
- README.rst
Description
-----------
Updates the `README.rst` file with more relevant content, reflecting the
new instructions for the Kubernetes setup.
Drive-by:
* Split `django-debug` target
Having a usefull README file to provide to people coming to the repository.
No tests were required.
- Documentation
Checklist
---------
> Update the README file

- .coafile
- Makefile
- api/apps/api/urls.py
- api/apps/api/views.py
- api/settings/base.py
- api/settings/local.py
- requirements.txt
Description
-----------
* Fix PyLint
* Fix CORS Headers issue
* Adjust Middleware settings for Django 2.0
* Fix `place/` endpoint
* Fix `django-debug` target to use the proper settings
The API server was not baheaving properly due to incorrect settings.
Manually.
Checklist
---------
> Fix various issues

- api/apps/api/urls.py
- api/apps/api/views.py
Description
-----------
The places endpoint was not taking the latitude/longitude as a parameter
and contained some hardcoded test data that needed to be cleaned up.
The endpoint is supposed to query the list of businesses nearby the marker on the map.
Manually.
Checklist
---------
> Fix the places/ endpoint

- Makefile
- README.rst
Description
-----------
This brings the relevant parts of the documentation from the `docs`
repository to the `README.rst` files of this project.
* Fix minor issues with the Makefile
* The `clean-*` targets were exiting with an error when there was
nothing to clean
* The RUN parameter is now `local` instead of `docker`
`make ci-docs`
- Documentation
Checklist
---------
> Update the docs

- Makefile
- charts/values.prod.yaml
Description
-----------
Updates the values of the api chart to deploy it to production.
The `Makefile` was updated as well, to add the production deployment
target.
- New feature (non-breaking change which adds functionality)
Checklist
---------
> Update production chart values

- api/apps/api/urls.py
Description
-----------
The API URLs got somehow messed up. This patch fixes them.
The API was not accessible.
Manually on the local minikube setup.
Checklist
---------
> Fix api URLs

- charts/values.minikube.yaml
- charts/values.prod.yaml
Description
-----------
Add values required to configured the Helm Chart used to deploy the API
to production.
Checklist
---------
> Fix helm values for minikube

- api/apps/api/urls.py
- api/urls.py
- charts/values.prod.yaml
Description
-----------
The routes were incorrectly defined, always redirecting to `/health`.
Fix the routes.
In the developer environment.
Checklist
---------
> Fix routes

- api/settings/base.py
- api/static.py
- docker/api/django-entrypoint.sh
Description
-----------
The API was failing to respond to queries dues to a missing favicon.
Make the API work.
In a dev environment.
Checklist
---------
Fixes request-yo-racks/api#36
> Fix missing static files

- charts/values.prod.yaml
Description
-----------
Adds TLS support to the ingress created to service the service.
- New feature (non-breaking change which adds functionality)
Checklist
---------
> Add TLS support

- api/settings/base.py
- api/settings/local.py
- api/settings/production.py
Description
-----------
Set the `CORS_ORIGIN_WHITELIST` to allow the `www` project to
communicate with the `api`.
Drive-by:
* Slightly reorganize the setting for more clarity and avoiding being
too permissive by mistake.
In a developer environment.
Checklist
---------
Fixes request-yo-racks/api#39
> Fix CORS settings for production

- charts/values.common.yaml
- charts/values.minikube.yaml
- charts/values.prod.yaml
Description
-----------
Clean up the chart values in a more logical way.
The behaoviors of the charts should be to de ready to deploy for
production, not for dev or testing.
By deploying to the dev environment.
Checklist
---------
> Clean up chart values

- .github/CONTRIBUTING.rst
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Documentation
Description
-----------
Updates the Github template to have similar and consistent templates
across all the RYR projects.
See above.
Checklist:
----------
> Update Github templates

- .gitignore
- Makefile
- api/settings/local.py
- docker/api/django-entrypoint.sh
- requirements.txt
- tools/kubernetes-django-env-vars.sh
Description
-----------
Makes the local environment more similar to the production one by using
gunicorn to serve the api, as well as setting up CORS and ALLOWED_HOSTS
settings to specific values rather than "all" (i.e. "*").
Being able to reproduce production errors in the development environment
more easily.
By running the developer environment locally.
Checklist:
----------
> Make environments more similar

- api/apps/api/collectors.py
- requirements.txt
Description
-----------
Uses a dataclass to specify which information will be returned by the API
in order to generate the email.
Checklist:
----------
Fixes request-yo-racks/api#22
> Implement a cleaner collector interface

- .gitignore
- api/apps/api/collectors.py
- api/apps/api/tests/test_collectors.py
- api/celery/tasks.py
- tox.ini
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
Description
-----------
Implements a function which merged 2 BusinessInfo objects together. Then
use this function to implement the `combine_collector_results` task
using the merge function
Add unit tests to validate the function.
Drive-by:
* Generate HTML report for coverage
* Update .gitignore
Being able to combine the results retrieved by the collectors.
* With unit tests.
* On a developer environment
Checklist:
----------
-  [X] I …
> Implement a merging mechanism

- .circleci/config.yml
- requirements.txt
Description
-----------
Installs Celery from the master branch to get python 3.7 support
Drive-by:
* Makes CircleCI configuration DRYer.
Checklist:
----------
> Install Celery from master branch

- tox.ini
Description
-----------
Tox runs from a cold start are lengthy (10+min) and heavy (1.2+GB).
This patch brings it down to ~8m30s and 950MB. The hot starts went
from ~1m30s to ~1min.
Checklist:
----------
> Optimize tox runs

- .circleci/config.yml
- README.rst
- Documentation
Description
-----------
Add coveralls badge and setup integration wit CircleCI.
Checklist:
----------
> Add coveralls

- Dockerfile
Description
-----------
Update the base python image to 3.7.1. This is required to use new
features like `dataclasses` for instance.
Checklist:
----------
> Update Docker Python image
